# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Test-API-App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore CleanUserApp.API/CleanUserApp.API.csproj

      - name: Build CleanUserApp.API
        run: dotnet build CleanUserApp.API/CleanUserApp.API.csproj --configuration Release

      - name: Publish CleanUserApp.API
        run: dotnet publish CleanUserApp.API/CleanUserApp.API.csproj -c Release -o ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./myapp
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1152945D94CF4B72908451804AC708F4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_245FD7C3B90F451E8EAB18A2E525753D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_41FE63FDB41448F5B2484C3EAC04CB6A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Test-API-App'
          slot-name: 'Production'
          package: ./myapp
          